### ISSUE TITLE
no more ftp

### ISSUE THREAD

**Issue by cwehmeyer** [markovmodel/mdshare#6]
I would prefer to not use FTP anymore in this package. Unfortunately, I don't know how to (easily) allow for wildcard use in file name pattern matching or the catalogue function without using FTP.

I thought about placing some kind of index file on the server but that would require quite some maintenance in the long run.

Any ideas, @marscher @clonker?

**Comment by marscher** [comment]
On 28.05.2018 16:58, Christoph Wehmeyer wrote:
> I would prefer to not use FTP anymore in this package. Unfortunately, I don't know how to (easily) allow for wildcard use in file name pattern matching or the catalogue function without using FTP.
> 
> I thought about placing some kind of index file on the server but that would require quite some maintenance in the long run.
> 
> Any ideas, @marscher @clonker?
> 

I've seen people parsing the html output of Apache for this job, but
this is however server dependent.
